#!/usr/bin/env python3
import sys


def solve(AtCoder: str, s: str, Contest: str):
    print(AtCoder[0]+s[0]+Contest[0])
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    AtCoder = next(tokens)  # type: str
    s = next(tokens)  # type: str
    Contest = next(tokens)  # type: str
    solve(AtCoder, s, Contest)

if __name__ == '__main__':
    main()
