#!/usr/bin/env python3
import sys

YES = "Yes"  # type: str
NO = "No"  # type: str


def solve(x: int, y: int):
    g1 = set([1, 3, 5, 7, 8, 10, 12])
    g2 = set([4, 6, 9, 11])
    g3 = set([2])

    if (x in g1 and y in g1) or (x in g2 and y in g2):
        print(YES)
    else:
        print(NO)
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    x = int(next(tokens))  # type: int
    y = int(next(tokens))  # type: int
    solve(x, y)

if __name__ == '__main__':
    main()
