#!/usr/bin/env python3
import sys
import itertools

def solve(N: int, A: "List[int]"):
    cands_total = [None]*N
    for i, ai in enumerate(A):
        cands_total[i] = range(max(0, ai-1), ai+1+1)

    cands_product = itertools.product(*cands_total)
    ans = 0
    for c in cands_product:
        for ci in c:
            if ci % 2 == 0:
                break
        else:
            continue

        ans += 1

    print(ans)
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    A = [int(next(tokens)) for _ in range(N)]  # type: "List[int]"
    solve(N, A)

if __name__ == '__main__':
    main()
