#!/usr/bin/env python3
import sys


def f(x):
    return x**2 + 2*x + 3


def solve(t: int):
    print(f(f(f(t)+t)+f(f(t))))
    return


# Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    t = int(next(tokens))  # type: int
    solve(t)


if __name__ == '__main__':
    main()
