#!/usr/bin/env python3
import sys


def solve(K: int):
    # 2, 20, 22, 200, 202, 220, 222,
    # (0), 1, 10, 11, 100, 101, 110, 111
    ans = []
    for x in bin(K)[2:]:
        ans.append([0, 2][int(x)])
    print("".join(map(str, ans)))
    return


# Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    solve(K)


if __name__ == '__main__':
    main()
