CONTEST=abc229
GEN_DIR=/Users/tkrk/Document_local/Documents/kyopuro/Contests
ATT=atcoder-tools
PROBLEM=A
ACTION=test
OPT=

gen:
	${ATT} gen ${CONTEST} --workspace ${GEN_DIR}

X:
	${ATT} ${ACTION} --dir ${CONTEST}/${PROBLEM} --code main.py ${OPT}
A:
	$(MAKE) X PROBLEM=A ACTION=submit
B:
	$(MAKE) X PROBLEM=B ACTION=submit
C:
	$(MAKE) X PROBLEM=C ACTION=submit
D:
	$(MAKE) X PROBLEM=D ACTION=submit
E:
	$(MAKE) X PROBLEM=E ACTION=submit
F:
	$(MAKE) X PROBLEM=F ACTION=submit
G:
	$(MAKE) X PROBLEM=G ACTION=submit
H:
	$(MAKE) X PROBLEM=H ACTION=submit
I:
	$(MAKE) X PROBLEM=I ACTION=submit
J:
	$(MAKE) X PROBLEM=J ACTION=submit
A-u:
	$(MAKE) X PROBLEM=A ACTION=submit OPT=-u
B-u:
	$(MAKE) X PROBLEM=B ACTION=submit OPT=-u
C-u:
	$(MAKE) X PROBLEM=C ACTION=submit OPT=-u
D-u:
	$(MAKE) X PROBLEM=D ACTION=submit OPT=-u
E-u:
	$(MAKE) X PROBLEM=E ACTION=submit OPT=-u
F-u:
	$(MAKE) X PROBLEM=F ACTION=submit OPT=-u
G-u:
	$(MAKE) X PROBLEM=G ACTION=submit OPT=-u
H-u:
	$(MAKE) X PROBLEM=H ACTION=submit OPT=-u
I-u:
	$(MAKE) X PROBLEM=I ACTION=submit OPT=-u
J-u:
	$(MAKE) X PROBLEM=J ACTION=submit OPT=-u

A-test:
	$(MAKE) X PROBLEM=A ACTION=submit
B-test:
	$(MAKE) X PROBLEM=B ACTION=submit
C-test:
	$(MAKE) X PROBLEM=C ACTION=submit
D-test:
	$(MAKE) X PROBLEM=D ACTION=submit
E-test:
	$(MAKE) X PROBLEM=E ACTION=submit
F-test:
	$(MAKE) X PROBLEM=F ACTION=submit
G-test:
	$(MAKE) X PROBLEM=G ACTION=submit
H-test:
	$(MAKE) X PROBLEM=H ACTION=submit
I-test:
	$(MAKE) X PROBLEM=I ACTION=submit
J-test:
	$(MAKE) X PROBLEM=J ACTION=submit
