#!/usr/bin/env python3
import sys
import re


def solve(s: str):
    # m = re.findall(r'A.*Z', s)
    # m = sorted(m)[-1]
    # print(len(m))

    l = -1
    r = 0
    for i, s_i in enumerate(s):
        if s_i == "A" and l == -1:
            l = i
        if s_i == "Z":
            r = i

    print(r - l + 1)
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    s = next(tokens)  # type: str
    solve(s)

if __name__ == '__main__':
    main()
