#!/usr/bin/env python3
import sys


def solve(A: int, B: int):
    A_ = str(A)
    B_ = str(B)
    Al = len(A_)
    Bl = len(B_)
    l = max(Al, Bl)
    ume = f"0{l}"
    A_ = format(A, ume)
    B_ = format(B, ume)
    for i in range(l):
        if int(A_[i]) + int(B_[i]) >= 10:
            print("Hard")
            return
    else:
        print("Easy")

    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    A = int(next(tokens))  # type: int
    B = int(next(tokens))  # type: int
    solve(A, B)


if __name__ == '__main__':
    main()
