#!/usr/bin/env python3
from typing import List
from collections import deque

# Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)


def main(N: int, X: int, L: List[int], a: List[List[int]]):
    q = deque([])
    for a0_i in a[0]:
        if X % a0_i == 0:
            q.append([X//a0_i, 1])
    ans = 0
    while q:
        rest, Ni = q.popleft()
        for aNi_i in a[Ni]:
            if rest < aNi_i:
                continue
            elif rest == aNi_i:
                if Ni == N-1:
                    ans += 1
                    continue
                elif Ni > N-1:
                    break
                else:
                    q.append([1, Ni+1])
                    continue
            if rest % aNi_i == 0:
                if Ni == N-1:
                    continue
                elif Ni > N-1:
                    break
                else:
                    q.append([rest // aNi_i, Ni+1])
                    continue
            else:
                continue
    print(ans)
    return


if __name__ == '__main__':
    N, X = map(int, input().split())

    L = []
    a = []
    for _ in range(N):
        t = list(map(int, input().split()))
        L.append(t[0])
        a.append(sorted(t[1:]))
    main(N, X, L, a)
