#!/usr/bin/env python3
from typing import List
from itertools import *

# Generated by 2.11.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)


def main(N: int, X: int, L: List[int], a: List[List[int]]):
    ans = 0
    for i in product(*a):
        mul = 1
        for x in i:
            mul *= x
        if mul == X:
            ans += 1
    print(ans)


if __name__ == '__main__':
    N, X = map(int, input().split())

    L = []
    a = []
    for _ in range(N):
        t = list(map(int, input().split()))
        L.append(t[0])
        a.append(sorted(t[1:]))
    main(N, X, L, a)
