#!/usr/bin/env python3
import sys
import math

def solve(K: int, S: int):
    ans = 0
    for x in range(K+1):
        if (S - x) > 2*K:
            continue
        for y in range(K+1):
            if (S - x - y) > K or (S - x - y) < 0:
                continue
            ans += 1

    print(ans)
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    S = int(next(tokens))  # type: int
    solve(K, S)

if __name__ == '__main__':
    main()
