#!/usr/bin/env python3
import sys
from collections import defaultdict

def dist(a, b):
    return int(((a-b)**2)**(1/2))

def solve(x: "List[int]", y: "List[str]"):
    print(dist(x[0], x[1]) + dist(y[0], y[1]) + 1)
    return


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    x = [0]*2
    y = [0]*2
    for i in range(2):
        x[i] = int(next(tokens))
        y[i] = int(next(tokens))

    solve(x, y)

if __name__ == '__main__':
    main()
