#!/usr/bin/env python3


# Generated by 2.9.0 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main(H: int, W: int, c: "List[str]"):
    for c_i in c:
        print(c_i)
        print(c_i)
    return

if __name__ == '__main__':
    H, W = map(int, input().split())
    C = [input() for _ in range(H)]
    main(H, W, C)
